### ISSUE TITLE
Add specs for stream.rb

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/manageiq-providers-azure#109]
We're currently at 0% coverage for stream.rb. The Amazon provider has some specs we can probably use as a baseline.

https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/stream_spec.rb

**Comment by djberg96** [comment]
@tumido Feel like taking a stab at this?

**Comment by tumido** [comment]
Sure, no problem. I'll take care of it, once I have a bit of time. ;)

**Comment by tumido** [comment]
@miq-bot assign @tumido

**Comment by tumido** [comment]
Let's try this again :wink: 

@miq-bot assign @tumido

**Comment by djberg96** [comment]
@tumido I don't suppose you ever got around to this, did you?

**Comment by tumido** [comment]
@djberg96 Sorry, it seems I didn't found the bit of time I was looking for. And it managed to slip between my fingers later on... :slightly_frowning_face: Hm.. I don't think I'll be able to help with this anymore. 

Apologies and condolences...

**Comment by djberg96** [comment]
Ok, closing.
