### ISSUE TITLE
Raise error if VM is generalized when requesting vm to start 

### ISSUE THREAD

**Issue by chris453** [ManageIQ/manageiq-providers-azure#112]
When running a HTTP request for ManageIQ to start a VM in azure will respond with a successful run when checking the status of task. But the VM will not be turned on since the VM is a generalized (image template) and cannot be started. 

Error in the evm.log show the error this should be raised to ensure people know the VM is not actually started 

 [----] E, [2017-08-16T11:10:07.643788 #2065:2af844831140] ERROR -- : MIQ(MiqQueue#m_callback) Message id: [1078]: [OperationNotAllowed] Operation 'start' is not allowed on VM 'USTest' since the VM is generalized. (cause: 409 Conflict)
[----] E, [2017-08-16T11:10:07.644041 #2065:2af844831140] ERROR -- : MIQ(MiqQueue#m_callback) backtrace: /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/azure-armrest-0.7.5/lib/azure/armrest/armrest_service.rb:252:in `raise_api_exception'

**Comment by djberg96** [comment]
This should be doable, though it will require an extra request on the backend because the status information is only available for the instanceView as part of the "status".

**Comment by djberg96** [comment]
I'm wondering if generalized vm's should be marked as not being publicly available.

**Comment by JPrause** [comment]
@djberg96 is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by djberg96** [comment]
It's still a potential issue, but it's not severe. If there's a BZ I'll work on it, but closing for now.
