### ISSUE TITLE
Downloading Orchestration Templates during Inventory Refresh can cause worker to exceed memory threshold  

### ISSUE THREAD

**Issue by blomquisg** [ManageIQ/manageiq-providers-azure#113]
Unfortunately, this is actually a guess right now.  But based on the log snipped below, it looks like the refresher is attempting to download templates when the refresh worker is killed for exceeding the memory threshold.

For this particular customer case, the customer increased the memory threshold and refreshes started working.

However, if there is a significantly large orchestration template in a customer's Azure inventory, this issue would likely come up again.

The Azure Inventory collector should probably not attempt to download all of the orchestration templates in the same process that's handling the general inventory collection.

One way to do that would be to create a skeleton record for the orchestration template, then queue up  separate downloads for each orchestration template.  This could allow the downloads to happen in parallel if necessary.  And, it would remove the memory footprint from the inventory collection process.

But, there's probably other ways to do this, too. 

Log snippet:
```
[----] I, [2017-08-15T12:05:28.160799 #15777:87d14c]  INFO -- : MIQ(ManageIQ::Providers::Azure::CloudManager::RefreshParser#ems_inv_to_hashes) Collecting data for EMS : [Azure-USEast] id: [10000000000012]...
[----] E, [2017-08-15T12:06:33.464578 #15777:87d14c] ERROR -- : MIQ(ManageIQ::Providers::Azure::CloudManager::RefreshParser#download_template) Failed to download Azure template <REDACTED>. Reason: #<RestClient::NotFound: 404 Not Found>
[----] E, [2017-08-15T12:06:34.477883 #15777:87d14c] ERROR -- : MIQ(ManageIQ::Providers::Azure::CloudManager::RefreshParser#download_template) Failed to download Azure template <REDACTED> Reason: #<RestClient::NotFound: 404 Not Found>
[----] E, [2017-08-15T12:06:47.122865 #15777:87d14c] ERROR -- : MIQ(ManageIQ::Providers::Azure::CloudManager::RefreshParser#download_template) Failed to download Azure template <REDACTED> Reason: #<RestClient::NotFound: 404 Not Found>
[----] E, [2017-08-15T12:07:00.357988 #15777:87d14c] ERROR -- : MIQ(ManageIQ::Providers::Azure::CloudManager::RefreshParser#download_template) Failed to download Azure template <REDACTED> Reason: #<RestClient::NotFound: 404 Not Found>
[----] E, [2017-08-15T12:07:34.617183 #15777:87d14c] ERROR -- : MIQ(ManageIQ::Providers::Azure::CloudManager::RefreshParser#download_template) Failed to download Azure template <REDACTED> Reason: #<RestClient::NotFound: 404 Not Found>
[----] I, [2017-08-15T12:07:49.424380 #6174:87d14c]  INFO -- : Q-task_id([log_status]) MIQ(ManageIQ::Providers::Azure::CloudManager::RefreshWorker#log_status) [Refresh Worker for Providers: Azure-USEast] Worker 
ID [10000001094878], PID [15777], GUID [8359f224-81d3-11e7-b79a-00505690684c], Last Heartbeat [2017-08-15 16:05:25 UTC], Process Info: Memory Usage [536494080], Memory Size [914935808], Proportional Set Size: [4
19259000], Memory % [4.32], CPU Time [1221.0], CPU % [0.0], Priority [27]
[----] I, [2017-08-15T12:12:44.412807 #6174:87d14c]  INFO -- : Q-task_id([log_status]) MIQ(ManageIQ::Providers::Azure::CloudManager::RefreshWorker#log_status) [Refresh Worker for Providers: Azure-USEast] Worker 
ID [10000001094878], PID [15777], GUID [8359f224-81d3-11e7-b79a-00505690684c], Last Heartbeat [2017-08-15 16:05:25 UTC], Process Info: Memory Usage [1851252736], Memory Size [2229260288], Proportional Set Size: 
[1705003000], Memory % [14.89], CPU Time [26348.0], CPU % [0.08], Priority [27]
[----] W, [2017-08-15T12:15:18.408088 #5959:87d14c]  WARN -- : MIQ(MiqServer#validate_worker) Worker [ManageIQ::Providers::Azure::CloudManager::RefreshWorker] with ID: [10000001094878], PID: [15777], GUID: [8359
f224-81d3-11e7-b79a-00505690684c] process memory usage [2312689000] exceeded limit [2147483648], requesting worker to exit
```

**Comment by djberg96** [comment]
Some initial attempts to improve this on the backend have been met with frustration. My initial thought was to perform a HEAD request against gallery templates, and compare MD5 values with what we store in our database. Unfortunately, the Azure gallery doesn't seem to allow HEAD requests, instead spitting a 405 at me.

I've also been trying to switch the azure-armrest gem from using rest-client to using oauth2/faraday in conjunction with net-http-persistent. In informal testing, I'm seeing a 40% speed increase and a 20% memory reduction. However, I've run into issues with faraday and oauth:

https://github.com/intridea/oauth2/issues/316
https://github.com/lostisland/faraday/issues/726

**Comment by Ladas** [comment]
https://github.com/ManageIQ/manageiq-providers-azure/pull/220 addresses the issue, for second refresh and beyond. We don't fetch the templates again, unless the Stack has been updated.

For first refresh, the only way is to do a collector, that fetches the data in small chunks and streams it to the persister worker. So it doesn't hold too many things in memory.
