### ISSUE TITLE
Missing Tenant ID when creating Provider using API

### ISSUE THREAD

**Issue by juliancheal** [ManageIQ/manageiq-providers-azure#197]
When creating an Azure provider using the API which includes via Ansible,
the `tenant_id` doesn't get set. As we're actually storing Azure's `tenant_id` in `uid_ems` internally.

So it should be:
```
miq.providers.create({
         :type => type,
         :provider_region => region,
         :name => name,
         :uid_ems => tenant_id,
         :subscription => subscription,
         :credentials => {
           :userid => userid,
           :password => password
          }
        })
```
not
```
miq.providers.create({
         :type => type,
         :provider_region => region,
         :name => name,
         :tenant_id => tenant_id,
         :subscription => subscription,
         :credentials => {
           :userid => userid,
           :password => password
          }
        })
```

<img width="535" alt="screen shot 2018-01-10 at 17 26 56" src="https://user-images.githubusercontent.com/63991/34788539-ca23209e-f632-11e7-8a69-1303e72d1a26.png">

**Comment by juliancheal** [comment]
@miq-bot assign juliancheal

**Comment by juliancheal** [comment]
If you use:

```
miq.providers.create({
         :type => type,
         :provider_region => region,
         :name => name,
         :azure_tenant_id => azure_tenant_id,
         :subscription => subscription,
         :credentials => {
           :userid => userid,
           :password => password
          }
        })
```

Which one would assume would work being as `azure_tenant_id` is an attribute on Azure::CloudManager https://github.com/ManageIQ/manageiq-providers-azure/blob/master/app/models/manageiq/providers/azure/cloud_manager.rb#L21

however this results in this error:

```
manageiq-api-client-0.2.0/lib/manageiq/api/client/connection.rb:106:in `check_response': Could not create the new provider - Invalid Provider attributes azure_tenant_id specified (RuntimeError)
```

**Comment by juliancheal** [comment]
This is being fixed via:

https://github.com/ManageIQ/manageiq-api/pull/279
https://github.com/ManageIQ/manageiq/pull/16802
https://github.com/ManageIQ/manageiq-providers-azure/pull/198

**Comment by djberg96** [comment]
As mentioned on gitter, a `tenant_id` is actually an association to the `tenants` table. The `azure_tenant_id` is a string used for Azure authentication.

**Comment by juliancheal** [comment]
Fixed! 🍰
