### ISSUE TITLE
Config options for API versions in Azure Stack

### ISSUE THREAD

**Issue by bsquizz** [ManageIQ/manageiq-providers-azure#259]
Azure stack can have a different set of API versions compared to the Azure public clouds. We'll need a way to either discover or set different versions for an Azure Stack provider and make sure that it does not interfere with the Azure providers.

Thoughts on this from @djberg96 
```
The library will automatically determine the latest api-version for each service. For manageiq, we'll need to decide on the semantics. At the moment it looks like this:

:ems:
  :ems_azure:
    :api_versions:
      :availability_set: "2017-12-01"
      :ip_address: "2017-11-01"

As I mentioned on the call, I'm thinking we change it to something like this:

:ems:
  :ems_azure:
    :default
      :api_versions:
        :availability_set: "2017-12-01"
        :ip_address: "2017-11-01"
    :your_provider
        :availability_set: "2016-11-30" # or whatever
        :ip_address: "2016-07-30" # ditto

If the provider name matches a config entry, we use those api-version strings. Otherwise we use the default settings.
```

**Comment by djberg96** [comment]
Going with this option instead: https://github.com/ManageIQ/manageiq-providers-azure/pull/275

In short, it will try to use the specified version. If it's invalid, it will use one of the supported api-versions. For cases where the service is not supported, e.g. managed images and disks, it's essentially ignored.
