### ISSUE TITLE
Azure Stack 

### ISSUE THREAD

**Issue by bronaghs** [ManageIQ/manageiq-providers-azure#268]
Below are the changes required to get the Azure Stack refresh working using the existing Azure Public cloud provider implementation:

- Azure stacks will pin to specific ARM API versions while the Public Cloud provider will use the latest version.  Ensure backward compatibility for stacks on older versions.
- Remove downcase of the flavor name for provisioning to work
- Refactor raw connect to support custom endpoint
- UI change to support custom endpoint

**Comment by bronaghs** [comment]
Spoke to PM (Brad Ascar). We should detect when an Azure Stack environment upgrades to a new version of an API, inform the user we detected this (maybe in EMS summary screen status field) and start automatically using the new version.

**Comment by JPrause** [comment]
@djberg96 is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by djberg96** [comment]
Going to close as another team is working on this now.
