### ISSUE TITLE
Timeouts during refresh cause refresh to crash

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [ManageIQ/manageiq-providers-azure#277]
If the refresh process experiences a timeout opening a connection to the Azure API, then the refresh process will crash. I think editing [this logic in the base armrest service class](https://github.com/ManageIQ/azure-armrest/blob/b69ff02ffc474b42873b2caebf835c00cfed0225/lib/azure/armrest/armrest_service.rb#L208-L228) to retry in the case of an `OpenTimeoutException` would help. Also the persistent connections that come with Excon would likely help as well, given that they were all timeouts while opening a socket, but I don't know how far out that may be.

**Comment by djberg96** [comment]
I don't know that we would want to put that in the azure-armrest gem directly, though we should at least make the timeout configurable: https://github.com/ManageIQ/azure-armrest/pull/302

The timeout handling should be within the provider code IMO.

**Comment by 01100010011001010110010101110000** [comment]
You're right it would be weird for a REST library to automatically retry a timeout exception like that, even one that's on socket open. Since most everything in the refresher either does a single `list_all` or calls to `gather_data_for_this_region`, do you think it would be a better idea to just wrap each call? It would be repetitive, but I don't think so much that it would make trying to refactor each method to use a central function worth it.

**Comment by djberg96** [comment]
Well, on further review, I think we're sort of already doing that by rescuing a 504. So really an `OpenTimeoutException` should already be getting caught and retried, shouldn't it? Or is the response code different?

**Comment by 01100010011001010110010101110000** [comment]
No, a 504 is would be if whatever web server between you and an app is unable to get a response from the app, like if puma was slow when running behind Apache. This `Azure::Armrest::OpenTimeoutException` exception is for when the TCP handshake to the web server can't even be completed, which is done when trying to open a socket to initiate any sort of communication with the Azure API. OpenTimeout -> No TCP socket -> no TCP -> no HTTP

**Comment by djberg96** [comment]
@01100010011001010110010101110000 See https://github.com/ManageIQ/manageiq-providers-azure/pull/278. In short, we've already got some hooks in the core AuthenticationMixin:

https://github.com/ManageIQ/manageiq/blob/d101c7997d556f08a7b0747703654ba74915b7da/app/models/mixins/authentication_mixin.rb#L236-L240

**Comment by 01100010011001010110010101110000** [comment]
Awesome, that wraps this up all rather neatly.
