### ISSUE TITLE
Unmanaged storage account lookup failure with targeted refresh

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/manageiq-providers-azure#301]
When performing a targeted refresh, unmanaged storage accounts are not necessarily going to be found. At the moment the ref is using the attached VM's resource group instead of the storage account's resource group. If those happen to be different then the lookup will fail.

The end result is that not only will the unmanaged storage account not be refreshed, but its `mode` will get set to null. You can see we don't ensure that `storage_acct` is defined first here:

https://github.com/ManageIQ/manageiq-providers-azure/blob/master/app/models/manageiq/providers/azure/inventory/parser/cloud_manager.rb#L190

A quick fix would be to make a check for `storage_acct` first. The better fix would be to set the ref properly.

**Comment by gtanzillo** [comment]
ping @djberg96

**Comment by djberg96** [comment]
@gtanzillo This was something that I discovered, it's not a customer issue, so it's on the backburner for now.
