### ISSUE TITLE
orchestration stack spec in core repo

### ISSUE THREAD

**Issue by durandom** [ManageIQ/manageiq-providers-azure#31]
There is still this https://github.com/ManageIQ/manageiq/blob/master/spec/models/manageiq/providers/azure/cloud_manager/orchestration_stack_spec.rb

can this be moved over here?

**Comment by durandom** [comment]
cc @bzwei

**Comment by djberg96** [comment]
Looks like it's already there:

https://github.com/ManageIQ/manageiq-providers-azure/blob/master/spec/models/manageiq/providers/azure/cloud_manager/orchestration_stack_spec.rb

So, it just needs to be removed from the core repo. I'll put in a PR today.

**Comment by bdunne** [comment]
Please cherry-pick https://github.com/ManageIQ/manageiq/commit/942ef0658f5dab4d3d0504ebd4d9cf95bcc7528c before closing this issue.

**Comment by djberg96** [comment]
@bdunne https://github.com/ManageIQ/manageiq-providers-azure/pull/35

**Comment by djberg96** [comment]
@durandom I believe you can close this now.
