### ISSUE TITLE
No metrics are collected

### ISSUE THREAD

**Issue by miha-plesko** [ManageIQ/manageiq-providers-azure#314]
I'm trying to get Azure metrics captured on latest master, but there seems to be empty intersection between expected metric names vs obtained metric names, so nothing gets collected. It's possible I'm just having something misconfigured, but can't seem to figure what.

It seems like here in this line:

https://github.com/ManageIQ/manageiq-providers-azure/blob/master/app/models/manageiq/providers/azure/cloud_manager/metrics_capture.rb#L210

We filter out too much, because `metrics_conn.list(...)` in L209 returns a list similar to
```
["/builtin/processor/percentiowaittime",
 "/builtin/processor/percentusertime",
 "/builtin/processor/percentnicetime",
 "/builtin/processor/percentprocessortime",
 "/builtin/processor/percentinterrupttime",
...
]
```
while COUNTER_NAMES that we're filtering against in L210 are similar to
```
set("\\Processor Information(_Total)\\% Processor Time",
 "\\Processor(_Total)\\% Processor Time",
 "\\Processor\\PercentProcessorTime",
..
)
```

Now I'm not sure what's causing the difference - did Azure start sending different metric names?

**Comment by djberg96** [comment]
@miha-plesko Those look new to me. It would seem MS altered the output without requiring an api-version change, so that sucks. Just running a local script I can see the api-version is hard-coded at 2014-04-01.

**Comment by miha-plesko** [comment]
@djberg96 I understand we currently pick metrics from Micosoft.Storage Table directly. Perhaps MS considers Table structure "private" and thus modifiable at any time even within same API version...

However, there seems to exist another approach, via Microsoft.Monitor provider that offers metrics via REST directly i.e. without messing with Table data, see https://docs.microsoft.com/en-us/rest/api/monitor/metrics/list. I've played with it a little and it seems to be working. So I'm wondering whether there is perhaps any hidden reason why we deal with Table data directly, besides the obvious fact that Microsoft.Monitor provider was not available at the time?

**Comment by djberg96** [comment]
@miha-plesko I think the main reason is that there weren't exact analogues to the existing metrics. However, they've been adding more over time, so maybe they exist now. If you can find the equivalent metrics using the newer API then please create a PR and we'll switch over.

**Comment by djberg96** [comment]
Mostly fixed by https://github.com/ManageIQ/manageiq-providers-azure/pull/335. @AlexanderZagaynov is still working on memory metrics. Closing for now.
