### ISSUE TITLE
add china region

### ISSUE THREAD

**Issue by e355312410** [ManageIQ/manageiq-providers-azure#324]
Is it possible to add china region ? thanks .

**Comment by djberg96** [comment]
We almost did before, but we didn't have any test credentials.

**Comment by e355312410** [comment]
> We almost did before, but we didn't have any test credentials.

good , mybe i can help for test , (-v-) ....

**Comment by djberg96** [comment]
@e355312410 You can follow https://github.com/ManageIQ/manageiq-providers-azure/pull/98 if you need guidance on submitting a PR of your own.
