### ISSUE TITLE
Azure Provider Last Refresh Error

### ISSUE THREAD

**Issue by click2cloud-vivekg** [ManageIQ/manageiq-providers-azure#433]
Hi, we are getting an error in the container it failed to encode ASCII-8BIT to UTF-8. These issues occur only in Azure Provider

Failed to encode

"\xEF" from ASCII-8BIT to UTF-8

[----] E, [2021-01-29T08:56:34.850698 #12923:10525fc] ERROR -- : [Encoding::UndefinedConversionError]: "\xEF" from ASCII-8BIT to UTF-8  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2021-01-29T08:56:34.989466 #12923:10525fc] ERROR -- : MIQ(MiqQueue#deliver) Message id: [208061], Error: ["\xEF" from ASCII-8BIT to UTF-8]
[----] E, [2021-01-29T08:56:34.990272 #12923:10525fc] ERROR -- : [ManageIQ::Providers::BaseManager::Refresher::PartialRefreshError]: "\xEF" from ASCII-8BIT to UTF-8  Method:[block (2 levels) in <class:LogProxy

**Comment by Fryguy** [comment]
@click2cloud-vivekg any updates?

**Comment by click2cloud-vivekg** [comment]
Its working for me
