### ISSUE TITLE
Bad request when getting metrics from koreacentral region

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-providers-azure#434]
`
[----] W, [2021-01-26T04:29:11.735097 #7:2b13dbeb395c] WARN -- : MIQ(ManageIQ::Providers::Azure::CloudManage r::MetricsCapture#perf_collect_metrics) Problem collecting metrics for [FILTERED]: [400 ] {"code":"BadRequest","message":"Failed to find metric configuration for provider: Microsoft.Compute, resour ce Type: virtualMachines, metric: Per Disk Read Bytes/sec, Valid metrics: Percentage CPU,Network In,Network O ut,Disk Read Bytes,Disk Write Bytes,Disk Read Operations/Sec,Disk Write Operations/Sec,CPU Credits Remaining, CPU Credits Consumed,Data Disk Read Bytes/sec,Data Disk Write Bytes/sec,Data Disk Read Operations/Sec,Data Di sk Write Operations/Sec,Data Disk Queue Depth,Data Disk Bandwidth Consumed Percentage,Data Disk IOPS Consumed Percentage,Data Disk Target Bandwidth,Data Disk Target IOPS,Data Disk Max Burst Bandwidth,Data Disk Max Burs t IOPS,Data Disk Used Burst BPS Credits Percentage,Data Disk Used Burst IO Credits Percentage,OS Disk Read By tes/sec,OS Disk Write Bytes/sec,OS Disk Read Operations/Sec,OS Disk Write Operations/Sec,OS Disk Queue Depth, OS Disk Bandwidth Consumed Percentage,OS Disk IOPS Consumed Percentage,OS Disk Target Bandwidth,OS Disk Targe t IOPS,OS Disk Max Burst Bandwidth,OS Disk Max Burst IOPS,OS Disk Used Burst BPS Credits Percentage,OS Disk U sed Burst IO Credits Percentage,Inbound Flows,Outbound Flows,Inbound Flows Maximum Creation Rate,Outbound Flo ws Maximum Creation Rate,Premium Data Disk Cache Read Hit,Premium Data Disk Cache Read Miss,Premium OS Disk C ache Read Hit,Premium OS Disk Cache Read Miss,VM Cached Bandwidth Consumed Percentage,VM Cached IOPS Consumed Percentage,VM Uncached Bandwidth Consumed Percentage,VM Uncached IOPS Consumed Percentage,Network In Total,N etwork Out Total"} (cause: 400 Bad Request). Region [koreacentral] may not be supported.
`

In contacting Microsoft, they stated that the request was wrong and recommended to edit from `%252C` to `%2C` when calling API to get data from Azure OCP cluster.  Unfortunately I don't have more information, nor a stack trace.

Since `%25` is the escape code for a literal `%` char, this seems like a double-escape bug.

**Comment by djberg96** [comment]
As I mentioned privately, if we had a double escape bug, I would think we would've seen it long before now. Without being able to see the request itself it's hard to say what's happening here. The region may be relevant. The first thing to check is that metrics are enabled for their region. I would like to see the output of the following CLI command:

`az provider show -n Microsoft.Insights`

In the meantime I'll see if I can create a VM in that region and collect metrics from our dev environment.

**Comment by Fryguy** [comment]
I'm trying to see if I can get the full request.  In the meantime I'll ask for that output.

**Comment by djberg96** [comment]
I was unable to duplicate this with a standalone script against a VM in the koreacentral region, but our metrics code required some extra steps at the time it was written because of shortcomings in azure-armrest that existed at the time. I'll do a bit more testing.

**Comment by chessbyte** [comment]
is there a benefit to moving from `azure-armrest` and towards https://github.com/Azure/azure-sdk-for-ruby ?  If so, any idea what level of effort that is?

**Comment by djberg96** [comment]
The level of effort would be high IMO. The azure-armrest gem hid some of the pain of stuff like collecting private images. That would have to be rewritten. The sdk is also much clumsier when it comes to api-version handling and locking. And those are just the things I can think of off the top of my head.

**Comment by djberg96** [comment]
Ok, I was able to recreate this using methods similar to what we use internally. I'll have to figure out what went wrong and where.

**Comment by djberg96** [comment]
I can duplicate it with a simple script like this, since the URL the provider code is cobbling together is basically what the `list_metrics` method does in azure-armrest:
```ruby
require 'azure-armrest'
require 'awesome_print'
require 'uri'

conf = Azure::Armrest::Configuration.new(#credentials)

vms = Azure::Armrest::VirtualMachineService.new(conf)
ims = Azure::Armrest::Insights::MetricsService.new(conf)
sas = Azure::Armrest::StorageAccountService.new(conf)

ims.api_version = '2018-01-01'

vm_name = 'korea-test-vm'
storage_name = 'dbergerdiag'
rgroup = 'dberger'

vm = vms.get(vm_name, rgroup)

metrics_names = [
  "Percentage CPU",
  "Per Disk Read Bytes/sec", # this seems to be an issue
  "Per Disk Write Bytes/sec", # and this
  "Network In Total",
  "Network Out Total"
]

start_time = Time.now.utc - 86400
end_time = Time.now.utc

options = {
  'timespan'    => "#{start_time.iso8601}/#{end_time.iso8601}",
  'interval'    => 'PT1M',
  #'metricnames' => metrics_names.join(','), # fails
  'metricnames' => "Percentage CPU,Network In Total", # works
  'aggregation' => 'Average',
}

definitions = ims.list_metrics(vm.id, options)
```
So either the Azure REST API is not handling commas in the metric name properly, or the name itself is just invalid. It's worked in the past, though, so I'm wondering if something's happened on the Azure side.

**Comment by djberg96** [comment]
Actually, the clue was in the error message. The problem isn't the encoding. The problem is that "Per Disk Read Bytes/sec" is not valid. The error message lists the valid metrics, and that's not one of them.

It definitely USED to be, so I'm not sure what's happening. You can see it listed here:

https://techdocs.broadcom.com/us/en/ca-enterprise-software/it-operations-management/application-performance-management/20-2/implementing-agents/infrastructure-agent/azure-monitoring/azure-metrics/Azure-Virtual-Machines.html

**Comment by djberg96** [comment]
IMO this is on Microsoft/Azure for removing a metric without tying it to an api-version string. Pretty terrible stuff really.

I only see 2 choices. The first option is to disable disk metrics for now. The second option is to find a suitable replacement, perhaps "OS Disk Read Bytes/sec".

**Comment by agrare** [comment]
It looks to me like they're trying to replace "Per Disk *" with "OS Disk *" and "Data Disk *" based on what is deprecated and what is preview.

The only metrics I see which isn't split across OS and Data disk are the "Disk Read Bytes" and "Disk Write Bytes".  If these are relative to the timespan and not aggregated could we do what we do on AWS which is basically `disk_usage_rate_average = (disk_read_bytes + disk_write_bytes) / interval` ?

**Comment by agrare** [comment]
> IMO this is on Microsoft/Azure for removing a metric without tying it to an api-version string. Pretty terrible stuff really.

This might be true, but given they're marked deprecated I doubt we'll convince them to undo this change

**Comment by djberg96** [comment]
@Fryguy The link you inserted does not contain a reference to the old metric.

**Comment by Fryguy** [comment]
It did when I posted it.  It seems Microsoft got around to removing it from the documentation.

**Comment by djberg96** [comment]
> It seems Microsoft got around to removing it from the documentation.

Which is why I didn't use their link. It's like 1984 with them.

**Comment by agrare** [comment]
So we've established that the metric we're trying to use doesn't exist anymore

**Comment by Fryguy** [comment]
Right, regardless of what link is posted we

1. Need a replacement or to remove the code
2. Need to understand why %252C is showing up, as it feels more coincidental that the missing metric was the one with the %252C, and hopefully reproduce _that_

**Comment by agrare** [comment]
> Need a replacement or to remove the code

https://github.com/ManageIQ/manageiq-providers-azure/issues/434#issuecomment-773311072 maybe?
