### ISSUE TITLE
The api-version for each service should be locked down

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/manageiq-providers-azure#45]
Each service class in the azure-armrest gem has its own api-version. This "api-version=" string is attached to every http request to Azure. By default it will use the latest non-preview version string.

Normally this is fine. However, on rare occasion Azure does alter the behavior of the request, typically by changing the output format. In such situations fixing it for a customer in the field would be difficult.

Therefore I think the api-version strings should be locked down to whichever version is being used while in testing and development prior to a major release. The easiest thing to do would be to store the api-version string in the config/settings.yml file. It will require a setting for each service class. Those that aren't set would default to the current api-version or use a `default` setting.

I'm thinking something along the lines of this:

```
:api_versions:
  :default: 2016-03-30
  :virtual_machine: 2017-03-30
  :ip_address: 2017-03-30
  :network_interface: 2017-04-01
  :storage: 2016-01-01
```

**Comment by djberg96** [comment]
@bronaghs @bzwei @durandom Thoughts?

**Comment by bzwei** [comment]
I agree.

**Comment by durandom** [comment]
Sounds good. Remember `settings.yml` is merged with the core settings. So nest this under `:ems_azure`

**Comment by djberg96** [comment]
@durandom Understood, thanks.

**Comment by djberg96** [comment]
https://github.com/ManageIQ/manageiq-providers-azure/pull/51
