### ISSUE TITLE
move service dialogs from core

### ISSUE THREAD

**Issue by durandom** [ManageIQ/manageiq-providers-azure#46]
https://github.com/ManageIQ/manageiq/pull/14668 has been merged. Now we can also seed `content/service_dialogs`. Looks like there is at least one for azure.

@djberg96 do you want to move this over here?

**Comment by djberg96** [comment]
@durandom I'll get a PR in today. What about `orchestration_templates`?

**Comment by durandom** [comment]
@djberg96 cool. 

> I'll get a PR in today. What about orchestration_templates?

Dont know :) Are they seeded like the dialogs?

**Comment by djberg96** [comment]
@bdunne Do you know the answer to that?

**Comment by bdunne** [comment]
Looks like seeding for that model needs to be updated for plugins as well.  I would expect them to move to `content/orchestration_templates/`.  cc @bzwei

**Comment by durandom** [comment]
@djberg96 @bzwei do you want to have a look at that? 
The dialog.rb and miq_dialog.rb do mostly the same.
Otherwise I'll do it.

**Comment by bzwei** [comment]
@durandom Go ahead. Thanks!

**Comment by djberg96** [comment]
Done!
