### ISSUE TITLE
UAE regions are missing

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-providers-azure#481]
Seems we need to refresh this.

I had a side-thought...I like that we come out of the box with pre-known regions.  When we do get credentials, however, if we find they are good, could we query for the regions list and merge it into the pre-known regions list?  Or is that not possible because they are on different workers?

**Comment by agrare** [comment]
:+1: https://github.com/ManageIQ/manageiq-providers-azure/pull/482 adds all of the current regions (including the two UAE ones) as well as a rake task to update them automatically in the future
