### ISSUE TITLE
Azure Discover process is failing with the below error "undefined method `address_prefix' for #<Azure::Armrest::Network::VirtualNetwork::Properties::Subnet::Properties:0x000..."

### ISSUE THREAD

**Issue by prasadanvekar** [ManageIQ/manageiq-providers-azure#547]
Azure discover process is failing to retrieve all the resources as the process failing with `"undefined method 'address_prefix' for #<Azure::Armrest::Network::VirtualNetwork::Properties::Subnet::Properties:0x000..."`

1. Add a Azure provider
2. wait for the discovery process to start. 
3. Error appears on the Azure provider summary page.
        

 -- Impacts all versions. Have tested on Najdorf, Oparin and Petrosian.
```
[----] E, [2024-02-07T19:17:20.223618 #3989007:93a8] ERROR -- evm: MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh) EMS: [CFX-Azure-USEast], id: [7] Unable to perform refresh for the following targets:
[----] E, [2024-02-07T19:17:20.223776 #3989007:93a8] ERROR -- evm: MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh)  --- ManageIQ::Providers::Azure::CloudManager [CFX-Azure-USEast] id [7]
[----] I, [2024-02-07T19:17:20.260304 #3989007:93a8]  INFO -- evm: MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh) Refreshing all targets...Complete
[----] E, [2024-02-07T19:17:20.260637 #3989007:93a8] ERROR -- evm: MIQ(MiqQueue#deliver) Message id: [19030211], Error: [undefined method `address_prefix' for #<Azure::Armrest::Network::VirtualNetwork::Properties::Subnet::Properties:0x0000556bc944e078>]
[----] E, [2024-02-07T19:17:20.260865 #3989007:93a8] ERROR -- evm: [ManageIQ::Providers::BaseManager::Refresher::PartialRefreshError]: undefined method `address_prefix' for #<Azure::Armrest::Network::VirtualNetwork::Properties::Subnet::Properties:0x0000556bc944e078>  Method:[block (2 levels) in <class:LogProxy>]
----] E, [2024-02-07T19:17:20.223510 #3989007:93a8] ERROR -- evm: /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-622e43171bad/app/models/manageiq/providers/azure/inventory/parser/network_manager.rb:87:in `block in cloud_subnets
'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-622e43171bad/app/models/manageiq/providers/azure/inventory/parser/network_manager.rb:82:in `each'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-622e43171bad/app/models/manageiq/providers/azure/inventory/parser/network_manager.rb:82:in `cloud_subnets'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-622e43171bad/app/models/manageiq/providers/azure/inventory/parser/network_manager.rb:77:in `block in cloud_networks'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-622e43171bad/app/models/manageiq/providers/azure/inventory/parser/network_manager.rb:66:in `each'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-622e43171bad/app/models/manageiq/providers/azure/inventory/parser/network_manager.rb:66:in `cloud_networks'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-622e43171bad/app/models/manageiq/providers/azure/inventory/parser/network_manager.rb:10:in `parse'
/var/www/miq/vmdb/app/models/manageiq/providers/inventory.rb:42:in `block in parse'
/var/www/miq/vmdb/app/models/manageiq/providers/inventory.rb:39:in `each'
/var/www/miq/vmdb/app/models/manageiq/providers/inventory.rb:39:in `parse'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:130:in `parse_targeted_inventory'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:95:in `block in refresh_targets_for_ems'
/opt/manageiq/manageiq-gemset/gems/more_core_extensions-4.4.0/lib/more_core_extensions/core_ext/benchmark/realtime_store.rb:20:in `realtime_store'
/opt/manageiq/manageiq-gemset/gems/more_core_extensions-4.4.0/lib/more_core_extensions/core_ext/benchmark/realtime_store.rb:56:in `realtime_block'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:94:in `refresh_targets_for_ems'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:41:in `block (2 levels) in refresh'
/opt/manageiq/manageiq-gemset/gems/more_core_extensions-4.4.0/lib/more_core_extensions/core_ext/benchmark/realtime_store.rb:20:in `realtime_store'
/opt/manageiq/manageiq-gemset/gems/more_core_extensions-4.4.0/lib/more_core_extensions/core_ext/benchmark/realtime_store.rb:62:in `realtime_block'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:41:in `block in refresh'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:31:in `each'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:31:in `refresh'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:11:in `refresh'
/var/www/miq/vmdb/app/models/ems_refresh.rb:71:in `block in refresh'
/var/www/miq/vmdb/app/models/ems_refresh.rb:70:in `each'
/var/www/miq/vmdb/app/models/ems_refresh.rb:70:in `refresh'
/var/www/miq/vmdb/app/models/miq_queue.rb:484:in `block in dispatch_method'
/usr/share/ruby/timeout.rb:95:in `block in timeout'
/usr/share/ruby/timeout.rb:33:in `block in catch'
/usr/share/ruby/timeout.rb:33:in `catch'
/usr/share/ruby/timeout.rb:33:in `catch'
/usr/share/ruby/timeout.rb:110:in `timeout'
/var/www/miq/vmdb/app/models/miq_queue.rb:482:in `dispatch_method'
/var/www/miq/vmdb/app/models/miq_queue.rb:459:in `block in deliver'
/var/www/miq/vmdb/app/models/user.rb:382:in `with_user_group'
/var/www/miq/vmdb/app/models/miq_queue.rb:459:in `deliver'
```

**Comment by agrare** [comment]
@prasadanvekar the "fix" can be relatively easy but I'd like to see what these subnets look like since a subnet without an addressPrefix isn't very helpful and I'm wondering if maybe there is some other option we need to look at.

Could you apply the following patch on your appliance and restart it, then get the logging output?

```
ssh to the appliance
# wget https://gist.githubusercontent.com/agrare/22b1bef6c6e1324fdc8e3bd4e40580b5/raw/40a9e2fbd69f8ed1ea692f313b1ae18a7c409e0b/network_manager.rb -O /tmp/network_manager.rb
# cd /var/www/miq/vmdb
# cd $(bundle show manageiq-providers-azure)
# cp /tmp/network_manager.rb app/models/manageiq/providers/azure/inventory/parser/network_manager.rb
# systemctl restart evmserverd.service
# journalctl -t evm -g TEST
```

**Comment by prasadanvekar** [comment]
@agrare Thanks for sharing the patch. I can see the error is not being displayed now and discovery process is able to collect all the resource details. 
Note: I have tested the patch on Najdorf 1.3 version.
Please find the log output below:
$ journalctl -t evm -g TEST
-- Logs begin at Tue 2024-02-06 10:54:47 EST, end at Thu 2024-02-08 12:14:43 EST. --
Feb 08 11:50:29 ip-172-31-17-92 evm[1128267]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: azrhelclisubnet1 properties: [{"name"=>"azrhelclisubnet1", "id"=>"/subscriptions/d843438e-c20d>
Feb 08 11:50:29 ip-172-31-17-92 evm[1128267]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: GatewaySubnet properties: [{"name"=>"GatewaySubnet", "id"=>"/subscriptions/d843438e-c20d-4954->
Feb 08 11:50:29 ip-172-31-17-92 evm[1128267]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: cxf-az-network-subnet1 properties: [{"name"=>"cxf-az-network-subnet1", "id"=>"/subscriptions/d>
Feb 08 11:50:29 ip-172-31-17-92 evm[1128267]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: default properties: [{"name"=>"default", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db>
Feb 08 11:50:29 ip-172-31-17-92 evm[1128267]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: default properties: [{"name"=>"default", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db>
Feb 08 11:50:29 ip-172-31-17-92 evm[1128267]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: virtual-node-aci properties: [{"name"=>"virtual-node-aci", "id"=>"/subscriptions/d843438e-c20d>
Feb 08 11:50:29 ip-172-31-17-92 evm[1128267]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: petrosiansubnet1 properties: [{"name"=>"petrosiansubnet1", "id"=>"/subscriptions/d843438e-c20d>
Feb 08 11:50:29 ip-172-31-17-92 evm[1128267]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: default properties: [{"name"=>"default", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db>
Feb 08 11:50:29 ip-172-31-17-92 evm[1128267]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: aks-subnet properties: [{"name"=>"aks-subnet", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-4>
Feb 08 11:50:29 ip-172-31-17-92 evm[1128267]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: morphy1envSubnet properties: [{"name"=>"morphy1envSubnet", "id"=>"/subscriptions/d843438e-c20d>
Feb 08 11:50:29 ip-172-31-17-92 evm[1128267]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: morphysubnet properties: [{"name"=>"morphysubnet", "id"=>"/subscriptions/d843438e-c20d-4954-91>
Feb 08 11:50:29 ip-172-31-17-92 evm[1128267]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: subnet1 properties: [{"name"=>"subnet1", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db>
Feb 08 11:50:29 ip-172-31-17-92 evm[1128267]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: subnet-1 properties: [{"name"=>"subnet-1", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615>
Feb 08 12:06:29 ip-172-31-17-92 evm[1129879]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: azrhelclisubnet1 properties: [{"name"=>"azrhelclisubnet1", "id"=>"/subscriptions/d843438e-c20d>
Feb 08 12:06:29 ip-172-31-17-92 evm[1129879]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: GatewaySubnet properties: [{"name"=>"GatewaySubnet", "id"=>"/subscriptions/d843438e-c20d-4954->
Feb 08 12:06:29 ip-172-31-17-92 evm[1129879]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: cxf-az-network-subnet1 properties: [{"name"=>"cxf-az-network-subnet1", "id"=>"/subscriptions/d>
Feb 08 12:06:29 ip-172-31-17-92 evm[1129879]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: default properties: [{"name"=>"default", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db>
Feb 08 12:06:29 ip-172-31-17-92 evm[1129879]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: default properties: [{"name"=>"default", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db>
Feb 08 12:06:29 ip-172-31-17-92 evm[1129879]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: virtual-node-aci properties: [{"name"=>"virtual-node-aci", "id"=>"/subscriptions/d843438e-c20d>
Feb 08 12:06:29 ip-172-31-17-92 evm[1129879]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: petrosiansubnet1 properties: [{"name"=>"petrosiansubnet1", "id"=>"/subscriptions/d843438e-c20d>
Feb 08 12:06:29 ip-172-31-17-92 evm[1129879]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: default properties: [{"name"=>"default", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db>
Feb 08 12:06:29 ip-172-31-17-92 evm[1129879]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: aks-subnet properties: [{"name"=>"aks-subnet", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-4>
Feb 08 12:06:29 ip-172-31-17-92 evm[1129879]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: morphy1envSubnet properties: [{"name"=>"morphy1envSubnet", "id"=>"/subscriptions/d843438e-c20d>
Feb 08 12:06:29 ip-172-31-17-92 evm[1129879]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: morphysubnet properties: [{"name"=>"morphysubnet", "id"=>"/subscriptions/d843438e-c20d-4954-91>
Feb 08 12:06:29 ip-172-31-17-92 evm[1129879]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: subnet1 properties: [{"name"=>"subnet1", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db>
Feb 08 12:06:29 ip-172-31-17-92 evm[1129879]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: subnet-1 properties: [{"name"=>"subnet-1", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615>
-- Reboot --
Feb 08 12:10:38 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: azrhelclisubnet1 properties: [{"name"=>"azrhelclisubnet1", "id"=>"/subscriptions/d843438e-c20d-49>
Feb 08 12:10:38 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: GatewaySubnet properties: [{"name"=>"GatewaySubnet", "id"=>"/subscriptions/d843438e-c20d-4954-91b>
Feb 08 12:10:38 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: cxf-az-network-subnet1 properties: [{"name"=>"cxf-az-network-subnet1", "id"=>"/subscriptions/d843>
Feb 08 12:10:38 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: default properties: [{"name"=>"default", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db3ee>
Feb 08 12:10:38 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: default properties: [{"name"=>"default", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db3ee>
Feb 08 12:10:38 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: virtual-node-aci properties: [{"name"=>"virtual-node-aci", "id"=>"/subscriptions/d843438e-c20d-49>
Feb 08 12:10:38 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: petrosiansubnet1 properties: [{"name"=>"petrosiansubnet1", "id"=>"/subscriptions/d843438e-c20d-49>
Feb 08 12:10:38 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: default properties: [{"name"=>"default", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db3ee>
Feb 08 12:10:38 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: aks-subnet properties: [{"name"=>"aks-subnet", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-4461>
Feb 08 12:10:38 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: morphy1envSubnet properties: [{"name"=>"morphy1envSubnet", "id"=>"/subscriptions/d843438e-c20d-49>
Feb 08 12:10:38 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: morphysubnet properties: [{"name"=>"morphysubnet", "id"=>"/subscriptions/d843438e-c20d-4954-91bc->
Feb 08 12:10:38 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: subnet1 properties: [{"name"=>"subnet1", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db3ee>
Feb 08 12:10:38 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: subnet-1 properties: [{"name"=>"subnet-1", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db3>
Feb 08 12:12:53 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: azrhelclisubnet1 properties: [{"name"=>"azrhelclisubnet1", "id"=>"/subscriptions/d843438e-c20d-49>
Feb 08 12:12:53 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: GatewaySubnet properties: [{"name"=>"GatewaySubnet", "id"=>"/subscriptions/d843438e-c20d-4954-91b>
Feb 08 12:12:53 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: cxf-az-network-subnet1 properties: [{"name"=>"cxf-az-network-subnet1", "id"=>"/subscriptions/d843>
Feb 08 12:12:53 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: default properties: [{"name"=>"default", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db3ee>
Feb 08 12:12:53 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: default properties: [{"name"=>"default", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db3ee>
Feb 08 12:12:53 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: virtual-node-aci properties: [{"name"=>"virtual-node-aci", "id"=>"/subscriptions/d843438e-c20d-49>
Feb 08 12:12:53 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: petrosiansubnet1 properties: [{"name"=>"petrosiansubnet1", "id"=>"/subscriptions/d843438e-c20d-49>
Feb 08 12:12:53 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: default properties: [{"name"=>"default", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db3ee>
Feb 08 12:12:53 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: aks-subnet properties: [{"name"=>"aks-subnet", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-4461>
Feb 08 12:12:53 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: morphy1envSubnet properties: [{"name"=>"morphy1envSubnet", "id"=>"/subscriptions/d843438e-c20d-49>
Feb 08 12:12:53 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: morphysubnet properties: [{"name"=>"morphysubnet", "id"=>"/subscriptions/d843438e-c20d-4954-91bc->
Feb 08 12:12:53 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: subnet1 properties: [{"name"=>"subnet1", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db3ee>
Feb 08 12:12:53 ip-172-31-17-92 evm[2976]:  INFO -- evm: MIQ(ManageIQ::Providers::Azure::Inventory::Parser::NetworkManager#cloud_subnets) TEST Subnet: subnet-1 properties: [{"name"=>"subnet-1", "id"=>"/subscriptions/d843438e-c20d-4954-91bc-44615db3>
lines 14-54/54 (END)

**Comment by agrare** [comment]
Thanks for getting this so quickly @prasadanvekar!  It looks like the journal output is being chopped off, could you redirect the output to a file like `journalctl -t evm -g TEST > output.log`

**Comment by prasadanvekar** [comment]
[output.log](https://github.com/ManageIQ/manageiq-providers-azure/files/14212715/output.log)
@agrare  PFA log.

**Comment by agrare** [comment]
Thanks @prasadanvekar so there is a single subnet that doesn't have an addressPrefix, `cxf-az-network-subnet1` but it does have a `routeTable`.  Is there anything particularly different about this subnet?  I can just skip the CIDR if azure can have subnets without an addressPrefix

**Comment by prasadanvekar** [comment]
@agrare i can see the addressPrefix  172.*.*.*/24 available for cxf-az-network-subnet1 in Azure. The only difference i can spot is it is connected to a NAT gateway.

**Comment by agrare** [comment]
Okay great let me see about replicating that in our azure environment
