### ISSUE TITLE
move azure specific events

### ISSUE THREAD

**Issue by durandom** [ManageIQ/manageiq-providers-azure#56]
similar to moving the settings we can also move event names (see [amazon](https://github.com/ManageIQ/manageiq-providers-amazon/pull/163/files) for an example)

**Comment by djberg96** [comment]
Don't we already have it?

https://github.com/ManageIQ/manageiq-providers-azure/blob/master/config/settings.yml#L15-L27

**Comment by durandom** [comment]
oops, indeed. I guess I looked at a stale clone...
thanks @djberg96
