### ISSUE TITLE
Performance and Utilisation does not work for Azure provider

### ISSUE THREAD

**Issue by borazem** [ManageIQ/manageiq-providers-azure#561]
# Issue description
After Azure cloud provider was configured and Performance and Utilization enabled in the `server roles` and in the Region `C & U Collection` and even one VM instance was deployed few days ago, the utilization is still not showing
<img width="1391" alt="image" src="https://github.com/user-attachments/assets/56bc1799-9c11-431f-ab10-7d2e3f6c76c8">
<img width="1403" alt="image" src="https://github.com/user-attachments/assets/55557e41-c0f5-4ece-b1d5-ff17fae3f9ae">
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/c2f7df4b-2747-4865-8bf2-ecfde36dc7b1">

The utilization however, works well for AWS cloud provider:
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/74d25a5c-6052-4bb6-9565-db93cc6f08c4">

# Environment
ManageIQ version: IA vmware based appliance 4.6.1

**Comment by agrare** [comment]
I see in your azure provider record: `capabilities: {"insights"=>false}` which means we aren't able to collect metrics for this provider.
`supports(:metrics) { _('Capacity & Utilization not supported for this region') unless insights? }`

**Comment by agrare** [comment]
I opened https://github.com/ManageIQ/manageiq-documentation/pull/1811 to document 1. that we require this resource provider to be able to fetch events / metrics and 2. how to enable it if it isn't already enabled.
