### ISSUE TITLE
Update regions.rb 

### ISSUE THREAD

**Issue by bronaghs** [ManageIQ/manageiq-providers-azure#77]
Support has been added for new Azure regions, therefore the regions.rb file needs updated to include them:

https://www.changedetection.com/log/microsoft/azure/regions_log.html

**Comment by djberg96** [comment]
We already have usgovtexas and usgovarizona, so I'm not sure why they show up as "new" regions. The only regions within the Americas that I see are the DoD regions, which are even more restrictive in terms of what Azure supports. Still want me to add those?

**Comment by bronaghs** [comment]
Hold off on DoD. Is our regions.rb file up to date with the regions listed on the Azure site?
 https://azure.microsoft.com/en-us/regions/?v=17.23h

**Comment by djberg96** [comment]
We don't have some of the european ones, e.g. Germany, but those aren't new. I can add them, though.

**Comment by djberg96** [comment]
Actually, I think the locations we don't currently support will require their own `Environment` classes. I'll need to dig.

**Comment by djberg96** [comment]
Leaving open for now, since we want to add China and Germany now.

**Comment by djberg96** [comment]
Germany added, China pending.

**Comment by djberg96** [comment]
Closing this. Germany was added, and other regions can be added as needed/requested.
