### ISSUE TITLE
503 while exporting templates

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [ManageIQ/manageiq-providers-azure#92]
I'm experiencing 503 errors during refresh for a couple of my subscriptions, one consistently and another intermittently. I found the stack traces for the errors, and they're identical for both subscriptions; they're posted [here](https://pastebin.com/ARh6PZ21)

It doesn't appear that there is anything wrong with the deployment templates that the refresher is attempting to export; I am able to export them without error from, e.g. [Resource Explorer](https://resources.azure.com)

If I can help with troubleshooting this, please let me know.

**Comment by djberg96** [comment]
I'm not actually sure how we should handle this, as it indicates a problem on the Azure side. This could actually be a scaling issue, possibly because we're making lots of requests under the hood in a short amount of time, something you're not doing with Resource Explorer.

@bzwei Suggestions?

**Comment by bzwei** [comment]
Can we use armrest gem to export the template from the problematic deployment? If yes, like what you suggested the problem may occur at the condition where lots of requests were made when doing the refresh.

**Comment by djberg96** [comment]
@bzwei Not sure what you mean, since it appears to be choking on `get_template` already.

**Comment by bzwei** [comment]
Try one single `get_template` using armrest gem without doing a refresh.

**Comment by 01100010011001010110010101110000** [comment]
I just attempted ```get_template``` on the same template as one of the failed exports, and it worked as expected

**Comment by djberg96** [comment]
@bzwei Maybe we should memoize the `get_template` method? How often do the templates change?

**Comment by djberg96** [comment]
Another option would be a retry with a delay of some sort.

My original plan was to do a HEAD request on the uri and do an MD5 comparison, but apparently Azure doesn't allow it.

**Comment by djberg96** [comment]
@01100010011001010110010101110000 Do you see any error's if you just run a plain script like this?

```
require 'azure-armrest'

conf = Azure::Armrest::Configuration.new(<your credentials here>)
tds = Azure::Armrest::TemplateDeploymentService.new(conf)

# Update region as appropriate
tds.list_all(:location => "eastus").each do |template|
  p template.name
  p tds.get_template(template.name, template.resource_group)
end
```

**Comment by 01100010011001010110010101110000** [comment]
I ran this against the same subscriptions I've been having trouble with, and it gave me no errors. That said, I was unable to provide the location key to ```list_all```, it doesn't appear to take any arguments because it's overwritten to use ```list_in_all_groups``` instead of the typical ```list_all``` method a ```ResourceGroupBasedService``` would use

**Comment by djberg96** [comment]
That's right, I forgot that template deployments don't have a location attribute. The best we could do would be to filter on the location of the underlying resource group, but I don't think we want to do that since there's no rule in Azure that says a resource group's resources must be in the same region.

In any case, it doesn't appear to be an issue with Azure directly then, but something about the interaction of ManageIQ and our code. I'm just not sure what yet.

**Comment by 01100010011001010110010101110000** [comment]
I tried more closely mimicking the way ManageIQ does this, which is to call ```list``` on the ```tds``` for every resource group; I still received no error.

**Comment by djberg96** [comment]
@01100010011001010110010101110000 Is there anything special about your local networking environment? Are you using a proxy for the app by any chance?

**Comment by 01100010011001010110010101110000** [comment]
We have a corporate FW which proxies SSL traffic (and does DPI on the proxied SSL and plaintext traffic), but the Azure endpoints are whitelisted and not proxied in that manner. 

Should I reboot reboot the appliance via ```appliance_console``` and see what happens on a full refresh?

**Comment by djberg96** [comment]
There are some SSL settings you could tinker with for the Configuration object (:ssl_version and :ssl_verify), though I don't know if it will help.

Yes, please try a reboot and see what happens. Couldn't hurt.

**Comment by 01100010011001010110010101110000** [comment]
So I bounced the appliance, and the problem subscription has yet to actually refresh. I watched as the refresh workers for each subscription each dialed a cpu core to 100%, and now the box is mostly idle and the refresh workers seem to all be sleeping, so I'm not sure what's occurred. 

I'm also experiencing some other issues, such as service requests not being picked up until I restart the appliance or the workers. That said, none of the subscriptions are giving a 503, and the most recent error on the failing subscription is ```[] Timed out connecting to server```, and from the logs it did timeout while collecting templates. 

I'm beginning to suspect that my efforts to investigate this may have made the appliance unstable, so I will deploy fine-3, move my automation domains and catalogs to it, and work from there.

**Comment by djberg96** [comment]
@01100010011001010110010101110000 Thanks for the update. Yes, definitely see if fine-3 helps at all. On a side note, I'm working on refactoring the underlying azure-armest gem to use faraday + net-http-persistent to see if that helps with speed, memory and general reliability as rest-client just isn't getting much love these days.

We'll see if that translates into improved reliability in general on the ManageIQ side. If not, it may be an uglier general architecture issue.

**Comment by djberg96** [comment]
(random side note - I now think of that alt-J song when i look at your username)

**Comment by 01100010011001010110010101110000** [comment]
I'm seeing similar behavior on fine-3, the initial refresh for the new appliance has been running for about 3 hours and hasn't completed. 

Have you considered using something like EventMachine to make calls asynchronously? It can still be used underneath Faraday, and I think that may help more with the amount of requests that have to be made than keeping a persistent connection and sleeping the thread until Azure replies, though I'm not an expert by any stretch. I'd like to help in this effort if possible, do you have any suggestions for starting places?

Random side note, I really like alt-J now, I hadn't heard of them before 👍

**Comment by djberg96** [comment]
@01100010011001010110010101110000 I haven't tried eventmachine, but it's easy enough to change the adapter. Right now you can look at the "faraday" branch for the azure-armrest gem if you're interested, though it's still in the middle of heavy refactoring and not yet suitable for plugging into your appliance.

**Comment by djberg96** [comment]
Just wanted to add a note that in the future, the azure-armrest gem will automatically retry requests in certain circumstances, include 503's.

https://github.com/ManageIQ/azure-armrest/pull/308

**Comment by 01100010011001010110010101110000** [comment]
Awesome. This issue hasn't cropped up for me in quite some time, and I never did track down an explanation which I really found satisfactory. The only change I've made to the code on my appliances is disabling unmanaged image gathering, so I wonder if the number of queries that was making is related.

**Comment by 01100010011001010110010101110000** [comment]
Haven't seen this a single time on `Fine-4` or later, going to go ahead and close.
