### ISSUE TITLE
Marketplace Image Support

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [ManageIQ/manageiq-providers-azure#94]
As talked about [here](http://talk.manageiq.org/t/deploying-azure-marketplace-images/2521) I'm opening an RFE for marketplace image support. From what I can see this will require:
* Altering ```prepare_for_clone_task``` to parse and accept marketplace URNs
* Adding a method to pull marketplace images to the refresh parser
* Maybe adding something akin to the public image settings and filter found in [the Amazon provider](https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/config/settings.yml)?

Related to ManageIQ/azure-armrest#288. Opening an issue on this project to reference in forthcoming PR

**Comment by djberg96** [comment]
@01100010011001010110010101110000 With https://github.com/ManageIQ/manageiq-providers-azure/pull/95 merged, can you close this?
